apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /data/datadir-mysql-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /data/datadir-mysql-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mysql-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /data/datadir-mysql-2/
